biblio/src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Author;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Resume;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isRead;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Person", inversedBy="books")
     */
    private $borrow;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->Resume;
    }

    public function setResume(?string $Resume): self
    {
        $this->Resume = $Resume;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->isRead;
    }

    public function setIsRead(bool $isRead): self
    {
        $this->isRead = $isRead;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getBorrow(): ?Person
    {
        return $this->borrow;
    }

    public function setBorrow(?Person $borrow): self
    {
        $this->borrow = $borrow;

        return $this;
    }
}

biblio/src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name', TextType::class, [
                'label' => 'Nom du livre *',
                'constraints' => [
                    new NotNull(),
                    new NotBlank(),
            ]])
            ->add('Author', TextType::class, [
                'label' => 'Nom de l\'auteur *',
                'constraints' => [
                    new NotNull(),
                    new NotBlank(),
            ]])
            ->add('Resume', TextareaType::class, [
                'label' => 'Un petit résumé',
                'constraints' => [
                    new Length([
                        'min' => 2,
                        'minMessage' => 'Le résumé ne peut pas être aussi court',
                    ])
                ]
            ])
            ->add('isRead', CheckboxType::class, [
                'label' => 'Déjà lu ? *',
                'required' => false
            ])
            ->add('borrow', null, [
                'label' => 'Emprunté par : ',
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

biblio/src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

  /**
     * @Route("/books", name="book_")
     */
class BookController extends AbstractController
{
    /**
     * @Route("/", name="browse")
     */
    public function browse(BookRepository $bookRepository)
    {
        $books = $bookRepository->findAll();

        return $this->render('book/browse.html.twig', [
            'controller_name' => 'BookController',
            'books' => $books
        ]);
    }
       /**
     * @Route("/{id}", name="read", requirements={"id":"\d+"})
     */
    public function read(Book $book)
    {
        return $this->render('book/read.html.twig', [
           'book' => $book
        ]);
    }
           /**
     * @Route("/{id}/edit", name="edit", requirements={"id":"\d+"})
     */
    public function edit(Book $book, Request $request, EntityManagerInterface $em)
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $book->setUpdatedAt(new \DateTime());

            $em->flush();

            return $this->redirectToRoute('book_read', ['id' => $book->getId()]);
        }

        return $this->render('book/edit.html.twig', [
           'form' => $form->createView(),
        ]);
    }
    
        /**
     * @Route("/add", name="add")
     */
    public function add(Request $request, EntityManagerInterface $em)
    {
        $book = new Book();

        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $em->persist($book);
            $em->flush();

            return $this->redirectToRoute('main');

        }

        return $this->render('book/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

biblio/templates/book/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biblio ~ Ajout d'un livre{% endblock %}

{% block body %}
<div class="container">

<div class="row">
<h1>Ajout d'un livre</h1>
</div>

<div class="container">
{{ form_start(form) }}

{{ form_row(form.Name) }}
{{ form_row(form.Resume) }}
{{ form_row(form.Author) }}
{{ form_row(form.isRead) }}
{{ form_row(form.borrow) }}

<button type="reset">Reset</button>
<button type="submit">Enregister</button>
{{ form_end(form) }}
</div>
</div>

{% endblock %}

biblio/templates/book/browse.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biblio ~ Liste des livres{% endblock %}

{% block body %}
<div class="container">

<div class="row">
<h1>
  Liste des livres
</h1>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Titre</th>
      <th scope="col">Auteur</th>
      <th scope="col">Resume</th>
      <th scope="col">Lu/ pas lu</th>
      <th scope="col">Emprunté par</th>
    </tr>
  </thead>
  <tbody>
  {% for book in books %}
    <tr class="table-{{ book.borrow is null ? 'light' : 'dark' }}">
      <td> <a href="{{ path('book_read', {'id' : book.id}) }}">
      {{book.name}}</a></td>
      <td>{{book.author}}</td>
      <td>{{book.resume|slice(0, 30)}}... <a class="text-muted" href="{{path('book_read', {'id' : book.id})}}">Lire la suite</a> </td>
      <td>{{book.isRead}}</td>
      <td>{{book.borrow}}</td>
    </tr>
 {% endfor %}
  </tbody>
</table> 

</div>
{% endblock %}

biblio/templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biblio ~ Edition d'un livre{% endblock %}

{% block body %}
<div class="container">

<div class="row">
<h1>Edition d'un livre</h1>
</div>

<div class="container">
{{ form_start(form) }}

{{ form_row(form.Name) }}
{{ form_row(form.Resume) }}
{{ form_row(form.Author) }}

{{ form_row(form.isRead) }}
{{ form_row(form.borrow) }}

<button type="reset">Reset</button>
<button type="submit">Enregister</button>
{{ form_end(form) }}
</div>
</div>

{% endblock %}

biblio/templates/book/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biblio ~ {{book.name}}{% endblock %}

{% block body %}
<div class="container">

<div class="card text-white bg-{{ book.isRead ? 'dark' : 'light' }} mt-3">
  <div class="card-header">Title: {{book.name}}</div>
  <div class="card-body">
    <h4 class="card-title">Auteur : {{book.author}}</h4>
    <p class="card-text">Résumé : {{book.resume}}</p>
  </div>
    <div class="card-footer text-muted">
    <div class="col-6">
    {{ book.isRead ? 'Déjà lu' : 'Pas encore lu' }}
    </div>
    <div class="col-4">
    Emprunteur : {{book.borrow}}
    </div>
    <div class="col-2">
    <a href="{{ path('book_edit', {'id' : book.id} ) }}">Edition</a>
    </div>
  </div>
</div>

</div>

{% endblock %}